### ISSUE TITLE
Week 4 Review

### ISSUE THREAD

**Issue by Anniechanster** [deltatrio/web-app#21]
User testing on different screens and walk through the app with a test group.

**Comment by kaylaobritsch** [comment]
This week we completed user testing for the first prototype. I was successful in taking the user testing comments and fixing the prototype. The new prototype has a much more focused main page—focusing on finding a random local beer.

The sprint failed this week because the second prototype has not been user tested yet. I didn't succeed in creating the first prototype because I didn't add enough interactive pages to user test (not every link was clickable). This was because I was focused on creating screens for all sizes. The second prototype has much more clickable links but only one screen size.

**Comment by Anniechanster** [comment]
Our team got most of everything done. The sprint failed as the interactive prototype had too little interactive components for users to accurately test it. Also, the second prototype has not been user tested.

After the interactive prototype was built, I did 3 user tests. However, this amount of testing was too little. We planned to do 3 user tests for each interviewer, but only 3 was completed. Then the suggestions were recorded and an issue was created for the prototype to be updated/improved. This version of the prototype is yet to be tested.

**Comment by Anniechanster** [comment]
@thomasjbradley
