### ISSUE TITLE
Weekly Review 7

### ISSUE THREAD

**Issue by Anniechanster** [deltatrio/web-app#53]
Complete final screens, make everything responsive, link, accessible, and work properly to ensure browser testing success.

**Comment by kaylaobritsch** [comment]
This week week I was successful by adding SEO, images and cleaning up the code for our web app. I also added a sign out and profile to the top navigation. This allows the users to go back to the app screen. Because coding this week was just fixing up the code it wasn't the most exciting and motivating.

We had a problem collaborating on GitHub this week. I had changed some file names when I was cleaning up the code and this caused some issues with the other coders. I should have been more transparent when I changed the file name and warned everyone beforehand.

**Comment by refkoer** [comment]
This week the sprint was successful because all the tasks were done on time. The group ran into a couple of problems but it was fixed with easily. 

I fixed the images, icons and small profile pictures for the recent page. This wa an issue from last week that we fixed and got done together as a team.

I wrote in the wrong file and kind of messed up github collaboration, but it was fixed as soon as it was brought to attention.

**Comment by Anniechanster** [comment]
In this week's sprint, the sprint succeeded because the tasks were completed and done on time. However, there was a bit of trouble with communication on GitHub.

I created the maps page where users can go to and see where they can get the specific beer they want. I embedded Google maps and made icons hover over map and made sure it was responsive.

**Comment by Anniechanster** [comment]
@thomasjbradley
